# Generated by Django 4.1.7 on 2023-03-23 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('isDone', models.BooleanField(default=False)),
                ('belongsTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.person')),
            ],
        ),
    ]
